;;; Compiled snippets and support files for `graphviz-dot-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'graphviz-dot-mode
		     '(("color" "color=${1:navyblue$$(yas/choose-value '(\"lightgrey\" \"pink\" \"maroon\" \"lightblue\" \"navyblue\"))}" "color=.." nil nil nil nil nil nil)
		       ("dir" "dir=${1:forward$$(yas/choose-value '(\"back\" \"both\" \"none\" \"forward\"))}" "dir=.." nil nil nil nil nil nil)
		       ("edge" "edge[style=${1:solid$$(yas/choose-value '(\"invis\" \"bold\" \"dashed\" \"dotted\" \"solid\"))} color=${2:navyblue$$(yas/choose-value '(\"lightgrey\" \"pink\" \"maroon\" \"lightblue\" \"navyblue\"))} dir=${3:forward$$(yas/choose-value '(\"back\" \"both\" \"none\" \"forward\"))} fontsize=${4:10}];" "edge[style=..,color=..]" nil nil nil nil nil nil)
		       ("lab" "label=\"$1\"" "label=\"..\"" nil nil nil nil nil nil)
		       ("node" "node[shape=${1:box$$(yas/choose-value '(\"record\" \"ellipse\" \"circle\" \"egg\" \"point\" \"plaintext\" \"box\"))} style=${2:rounded$$(yas/choose-value '(\"dashed\" \"dotted\" \"solid\" \"bold\" \"filled\" \"rounded\"))} color=${3:lightskyblue$$(yas/choose-value '(\"lightgray\" \"lightpink\" \"lightsalmon\" \"lightblue\" \"lightskyblue\"))} fontsize=\"${4:12}\"];" "node[shape=..,color=..]" nil nil nil nil nil nil)
		       ("rankdir" "rankdir=${1:LR$$(yas/choose-value '(\"BL\" \"BR\" \"TL\" \"TR\" \"RB\" \"RT\" \"LB\" \"LT\" \"LR\"))}" "rankdir=.." nil nil nil nil nil nil)
		       ("shape" "shape=${1:box$$(yas/choose-value '(\"record\" \"ellipse\" \"circle\" \"egg\" \"point\" \"plaintext\" \"box\"))}" "shape=.." nil nil nil nil nil nil)
		       ("subgraph" "subgraph cluster_$1 {\n    style=${2:filled$$(yas/choose-value '(\"bold\" \"rounded\" \"filled\"))};\n	color=${3:lightgray$$(yas/choose-value '(\"lightpink\" \"lightsalmon\" \"lightblue\" \"lightskyblue\" \"lightgray\"))};\n	label=\"$4\";\n    $0\n}" "subgraph { .. }" nil nil nil nil nil nil)
		       ("tpl" "\ndigraph G {\n    compound=true;\n    // rankdir=LR;\n	size=\"6,6\";\n\n    $0\n\n    // optional, node statement\n    node [shape=box] box1 box2;\n	node [shape=ellipse] {node [label=\"same\"] same1 same2} ellipse;\n\n    // usually, node define\n    // default type is ellipse\n    box1 box2 [style=filled, fillcolor=yellow];\n    // define record type\n    n1 [shape=record, label=\"{a|<f1>b|c}\"];\n\n    // subgraph statement\n    subgraph cluster_1 {\n        style=filled;\n    	label=\"Sub Graph\";\n    	color=lightgrey;\n\n        box1 -> same1 -> n1;\n    }\n\n    edge [color=lightblue, fontsize=10, fontcolor=navyblue];\n    ellipse -> same2 [lable=\"test line\"];\n    box2 -> same2 -> n1:f1 [style=dotted, color=blue];\n\n    label = \"\\n\\nSample Digraph\\ndrawn by `(user-full-name)`\";\n    fontsize=20;\n}" "A digraph example" nil nil nil nil nil nil)
		       ("tpl1" "\ngraph G {\n    compound=true;\n    // rankdir=LR;\n	size=\"6,6\";\n\n    $0\n\n    // optional, node statement\n    node [shape=box] box1 box2;\n	node [shape=ellipse] {node [label=\"same\"] same1 same2} ellipse;\n\n    // usually, node define\n    // default type is ellipse\n    box1 box2 [style=filled, fillcolor=yellow];\n    // define record type\n    n1 [shape=record, label=\"{a|<f1>b|c}\"];\n\n    // subgraph statement\n    subgraph cluster_1 {\n        style=filled;\n    	label=\"Sub Graph\";\n    	color=lightgrey;\n\n        box1 -- same1 -- n1;\n    }\n\n    edge [color=red]\n    ellipse -- same2 [lable=\"test line\"];\n    box2 -- same2 -- n1:f1 [style=dotted, color=blue];\n\n    label = \"\\n\\nSample Graph\\ndrawn by `(user-full-name)`\";\n    fontsize=20;\n}\n" "a graph example" nil nil nil nil nil nil)))


;;; Do not edit! File generated at Wed Apr 17 16:58:17 2013
